server:
  port: 8084
 
mybatis:
  mapper-locations: classpath:*-mapper.xml 
  configuration:
    map-underscore-to-camel-case: true
   
spring:
  application:
    name: msa-coffee-order-status
  datasource:
    url: jdbc:h2:tcp://localhost/~/shqkeldb
    driverClassName: org.h2.Driver
    username: shqkel
    password: shqkel
# 아래는 Deprecated.
#    initialization-mode: always
#    schema: classpath:h2/schema.sql
#    data: classpath:h2/data.sql
  sql:
    init:
      mode: always
      schema-locations:
      - classpath:h2/schema.sql
#      data-locations:
#      - classpath:h2/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console